version: '3.8'

services:
  db:
    image: mysql:9.0
    container_name: mysql_db1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecole
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  php:
    image: php:8.2-apache
    container_name: php_app
    volumes:
      - ./app:/var/www/html
    ports:
      - "8085:80"
    depends_on:
      - db
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    ports:
      - "8086:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
